In [28]:
# Imports
from imblearn.pipeline import Pipeline  # imblearn's pipeline supports resampling steps
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np
import os
# Disable tokenizers parallelism to avoid deadlocks
os.environ["TOKENIZERS_PARALLELISM"] = "false"
import torch
import re
from torch.nn import CrossEntropyLoss
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import accelerate
import optuna
from sklearn.metrics import precision_recall_fscore_support, accuracy_score
torch.cuda.is_available()

True

In [29]:
directory = r"/home/noarchway/PycharmProjects/threat-monitor/Classifier/dataset"
df = pd.DataFrame()
for name in os.listdir(directory):
    with open(os.path.join(directory, name)) as f:
        print(f"Content of '{name}'")
        csvdf = pd.read_csv(f)
        df = pd.concat([df, csvdf])
print("Original df shape:", df.shape)

Content of 'output_04.csv'
Content of 'output_05.csv'
Content of 'output_03.csv'
Content of 'output_06.csv'
Content of 'output_02.csv'
Content of 'output_01.csv'
Original df shape: (509073, 15)

In [30]:
# Create a new DataFrame with only the necessary columns and rename them
values = df[['Rating', 'Content']].copy()
values.rename(columns={'Rating': 'label', 'Content': 'text'}, inplace=True)
# Map ratings: 1 and 2 become 0; 3, 4, 5 (and NaN) become 1
values['label'] = values['label'].map({1: 0, 2: 0, 3: 1, 4: 1, 5: 1, np.nan: 1})
values.dropna(subset=['text'], inplace=True)

# Convert columns to lists for tokenization
texts = values['text'].tolist()
labels = values['label'].tolist()

def normalize_text(text):
    # Remove HTML tags if any
    text = re.sub(r'<.*?>', '', text)
    # Remove extra whitespace and strip leading/trailing spaces
    text = re.sub(r'\s+', ' ', text).strip()
    # Convert text to lowercase (optional since the model is uncased)
    text = text.lower()
    return text

# Apply normalization to your texts
texts = [normalize_text(t) for t in texts]

# Split into training and test sets
train_texts, test_texts, train_labels, test_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

Tokenize all of the text, essentially tokenizing will return a list of lists with additional data. The lists are individual texts and labels that get encoded so broken down into tokens and then returns the list of id's that make up that text and gets padded out to length 128

In [31]:
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Tokenize the text, breaks the text down into tokens and encodes the location like a hashmap
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=128)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=128)

# Create a PyTorch dataset
class TextDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = TextDataset(train_encodings, train_labels)
test_dataset = TextDataset(test_encodings, test_labels)

In [32]:
# Class frequencies
freq_0 = 87192
freq_1 = 12808
total_samples = freq_0 + freq_1  # 100000 in this example
num_classes = 2

# Compute weights: total_samples / (num_classes * class_frequency)
w0 = total_samples / (num_classes * freq_0)
w1 = total_samples / (num_classes * freq_1)

# Now create a tensor for the weights
class_weights = torch.tensor([w0, w1]).float().cuda()  # If you're using GPU

print("Class Weights:", class_weights)

Class Weights: tensor([0.5734, 3.9038], device='cuda:0')

In [33]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights = torch.tensor([w0, w1]).float().to(device)

class WeightedModel(torch.nn.Module):
    def __init__(self, base_model, weights):
        super().__init__()
        self.base_model = base_model
        self.weights = weights

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        # Remove the extra keyword if it exists
        kwargs.pop('num_items_in_batch', None)
        # Call the base model without the unexpected argument
        outputs = self.base_model(input_ids, attention_mask=attention_mask, labels=None, **kwargs)
        logits = outputs.logits
        if labels is not None:
            loss_fct = torch.nn.CrossEntropyLoss(weight=self.weights)
            loss = loss_fct(logits, labels)
            return (loss, logits)
        return (logits,)

base_model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)
model = WeightedModel(base_model, class_weights)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [34]:


model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='binary')
    accuracy = accuracy_score(labels, preds)
    return {'accuracy': accuracy, 'precision': precision, 'recall': recall, 'f1': f1}

def model_init():
    base_model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
    weighted_model = WeightedModel(base_model, class_weights)
    return weighted_model


def objective(trial):
    training_args = TrainingArguments(
        output_dir="./results",
        num_train_epochs=3,
        per_device_train_batch_size=32,
        per_device_eval_batch_size=64,
        learning_rate=2.2786275995431975e-05,
        weight_decay=0.00010005716374558712,
        eval_strategy="epoch",
        save_strategy="epoch",
        logging_dir='./logs',
        load_best_model_at_end=True,
        metric_for_best_model="f1"
    )

    trainer = Trainer(
        model_init=model_init,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics,
    )

    try:
        trainer.train()
        eval_result = trainer.evaluate()
        return eval_result["eval_f1"]
    except Exception as e:
        print(f"Trial failed due to: {e}")
        return 0.0  # Return a minimal value to ignore this trial

In [35]:
study = optuna.create_study(direction="maximize")  # maximize the F1-score
study.optimize(objective, n_trials=10)

print("Best trial:")
trial = study.best_trial

print(f"  F1: {trial.value}")
print("  Best hyperparameters:")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

[I 2025-04-03 20:29:06,768] A new study created in memory with name: no-name-c5afb08a-70da-4a88-b154-fc3e33d15633
/tmp/ipykernel_206918/1170152378.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate=trial.suggest_loguniform("learning_rate", 5e-6, 5e-4),
/tmp/ipykernel_206918/1170152378.py:24: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay=trial.suggest_loguniform("weight_decay", 1e-5, 1e-2),
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-04-03 21:52:28,610] Trial 0 finished with value: 0.7505563994771611 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 32, 'learning_rate': 2.2786275995431975e-05, 'weight_decay': 0.00010005716374558712}. Best is trial 0 with value: 0.7505563994771611.
/tmp/ipykernel_206918/1170152378.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate=trial.suggest_loguniform("learning_rate", 5e-6, 5e-4),
/tmp/ipykernel_206918/1170152378.py:24: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay=trial.suggest_loguniform("weight_decay", 1e-5, 1e-2),
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[I 2025-04-03 23:27:38,281] Trial 1 finished with value: 0.6075718720475097 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 16, 'learning_rate': 7.750458657601906e-05, 'weight_decay': 6.381823894589006e-05}. Best is trial 0 with value: 0.7505563994771611.
/tmp/ipykernel_206918/1170152378.py:23: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate=trial.suggest_loguniform("learning_rate", 5e-6, 5e-4),
/tmp/ipykernel_206918/1170152378.py:24: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  weight_decay=trial.suggest_loguniform("weight_decay", 1e-5, 1e-2),
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[W 2025-04-03 23:38:22,921] Trial 2 failed with parameters: {'num_train_epochs': 5, 'per_device_train_batch_size': 8, 'learning_rate': 1.7991462496474703e-05, 'weight_decay': 0.0007341405950115151} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipykernel_206918/1170152378.py", line 41, in objective
    trainer.train()
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 2245, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 2556, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 3764, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/accelerate/accelerator.py", line 2454, in backward
    loss.backward(**kwargs)
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/home/noarchway/PycharmProjects/threat-monitor/.venv/lib/python3.12/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-04-03 23:38:22,926] Trial 2 failed with value None.

KeyboardInterrupt:

In [36]:
# Best trial
trial = study.best_trial

print("Best F1-score:", trial.value)
print("Best Hyperparameters:")
for key, value in trial.params.items():
    print(f"  {key}: {value}")

Best F1-score: 0.7505563994771611
Best Hyperparameters:
  num_train_epochs: 4
  per_device_train_batch_size: 32
  learning_rate: 2.2786275995431975e-05
  weight_decay: 0.00010005716374558712